# eslint config

# Rules reference:
# http://eslint.org/docs/rules/
extends: 'eslint:recommended'
env:
  browser: true
  es6: true
parserOptions:
  sourceType: module

rules:
  indent:
    - 2
    - 2
  linebreak-style:
    - 1
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
