# sass-lint config originally based on AirBnB SCSS Coding Standard
# https://github.com/airbnb/css
# Modified for custom use by Copious.

# Rules reference:
# https://github.com/sasstools/sass-lint/tree/master/docs/rules

options:
  formatter: stylish
  merge-default-rules: true
rules:
  bem-depth: 1
  border-zero:
    - 1
    - convention: '0'
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  clean-import-paths: 1
  empty-args: 1
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - allow-leading-underscore: false
  hex-length: 1
  hex-notation: 1
  id-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 1
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 1
  one-declaration-per-line: 1
  placeholder-in-extend: 0
  property-sort-order:
    - 1
    - order: 'alphabetical'
  property-units:
    - 1
    - global:
        - em
        - rem
        - px
        - s
        - vh
        - vw
        - vmin
        - vmax
        - '%'
  pseudo-element: 1
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 1
    - allowed-shorthands:
      - 1
      - 2
  single-line-per-selector: 1
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 1
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 1
  trailing-semicolon: 2
  url-quotes: 1
  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit: 1
